config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks do
    collection do
      get 'search'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :update]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :tidies, dependent: :destroy
  has_many :tasks, through: :tidies
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :tidies, dependent: :destroy
  has_many :labels, through: :tidies
  validates :task_name, :task_detail, :expiry_date, presence: true

  enum status: {
    未着手: 1,
    着手中: 2,
    完了: 3
  }

  enum priority:{
    低: 1,
    中: 2,
    高: 3
  }

  scope :recent_order, -> {order(created_at: :desc)}
  scope :expiry_order_desc, -> {order(expiry_date: :desc)}
  scope :expiry_order_asc, -> {order(expiry_date: :asc)}
  scope :priority_order_desc, -> {order(priority: :desc)}
  scope :priority_order_asc, -> {order(priority: :asc)}

  def self.search(search)
    search[:keyword] = nil if search[:status].blank?
    search[:status] = nil if search[:status].blank?
    if search[:label_id].blank?
      search[:label_id] = nil
    else
      task_id = Tidy.where(label_id: search[:label_id]).pluck(:task_id)
    end
    if search[:keyword] && search[:status] && search[:label_id]
      Task.where("task_name LIKE ?", "%#{search[:keyword]}%").where(status: search[:status]).where(id: task_id)
    elsif search[:keyword] && search[:status]
      Task.where("task_name LIKE ?", "%#{search[:keyword]}%").where(status: search[:status])
    elsif search[:keyword] && search[:label_id]
      Task.where("task_name LIKE ?", "%#{search[:keyword]}%").where(id: task_id)
    elsif search[:status] && search[:label_id]
      Task.where(status: search[:status]).where(id: task_id)
    elsif search[:keyword]
      Task.where("task_name LIKE ?", "%#{search[:keyword]}%")
    elsif search[:status]
      Task.where(status: search[:status])
    elsif search[:label_id]
      Task.where(id: task_id)
    else
      Task.all
    end
  end

  def self.sort_search(search)
    if search[:sort_keyword] == "期限▼"
      Task.search(search).expiry_order_desc
    elsif search[:sort_keyword] == "期限▲"
      Task.search(search).expiry_order_asc
    elsif search[:sort_keyword] == "優先▼"
      Task.search(search).priority_order_desc
    elsif search[:sort_keyword] == "優先▲"
      Task.search(search).priority_order_asc
    else
      Task.search(search).recent_order
    end
  end
end

app/models/tidy.rb
class Tidy < ApplicationRecord
  belongs_to :label
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :admin_not_delete
  before_update :admin_not_update
  has_many :tasks, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  validates :password, length: { minimum: 6}

  private

  def admin_not_delete
    throw(:abort) if User.where(admin: true).count == 1 && self.admin == true
  end

  def admin_not_update
    throw(:abort) if User.where(admin: true).count == 1 && will_save_change_to_attribute?(:admin, to: false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :only_admin

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice:"作成しました"
    else
      render :new
    end
  end

  def update
    set_user
    if @user.update(user_params)
      redirect_to admin_users_path, notice:"更新しました"
    else
      render :edit
    end

  end

  def show
    set_user
  end

  def edit
    set_user
  end

  def destroy
    set_user
    if @user.destroy
      redirect_to admin_users_path, notice:"削除しました"
    else
      render :edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_digest, :admin)
  end


  def only_admin
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = "管理者以外はアクセスできません"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to user_path(current_user.id) if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks.includes(:labels).recent_order.page(params[:page])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice:"登録しました"
    else
      render :new
    end
  end

  def show
    set_task
  end

  def edit
    set_task
  end

  def update
    set_task
    if @task.update(task_params)
      redirect_to tasks_path, notice:"更新しました"
    else
      render :edit
    end
  end

  def destroy
    set_task
    if @task.destroy
      redirect_to tasks_path, notice:"削除しました"
    end
  end

  def search
    search_params
    set_search_keyword(@search)
    if @search.present?
      @tasks = current_user.tasks.sort_search(@search).includes(:labels).page(params[:page])
    end
    @tasks ||= current_user.tasks.includes(:labels).recent_order.page(params[:page])
    render :index
  end

  private

  def set_search_keyword(search)
    @keyword = search[:keyword]
    @status = search[:status]
    @sort_keyword = search[:sort_keyword]
    @label_keyword = search[:label_id]
  end

  def search_params
    @search = params.require(:task).permit(:keyword, :status, :sort_keyword, :label_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    @task = params[:task].permit(:task_name, :task_detail, :expiry_date, :status, :priority, :user_id, label_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to user_path(current_user.id) if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    set_user
    redirect_to tasks_path unless @user.id == current_user.id
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name,
                          :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="login_form">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "個エラー") %> があります。 <%= @user.name %> </h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <%= f.text_field :name,  placeholder: "名前", class: "form-control mb-3" %>
    <%= f.email_field :email, placeholder: "メールアドレス", class: "form-control mb-3"  %>
    <%= f.select :admin, ["true","false"], {},class: "form-control mb-3" %>
    <%= f.password_field :password, placeholder: "パスワード", class: "form-control mb-3" %>
    <%= f.password_field :password_confirmation, placeholder: "パスワード確認", class: "form-control" %>
    <div class="text-center">
      <%= f.submit class: "btn btn-primary mt-3 text-center w-100" %>
    </div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h3 class="text-center mt-3">管理画面からユーザー編集</h3>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="content">
  <h1>ユーザー管理画面</h1>
  <p id="notice"><%= notice %></p>
  <%= link_to 'ユーザーを登録する', new_admin_user_path, class: 'btn btn-primary mb-3', id: "user_create" %>
  <table class="table list">
    <thead>
      <tr>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th>タスク数</th>
        <th>管理権限</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="">
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.count %></td>
          <td><%= user.admin %></td>
          <td><%= link_to '詳細', admin_user_path(user), class: "btn btn-outline-primary btn-sm", id: "user_detail"%></td>
          <td><%= link_to '編集', edit_admin_user_path(user), class: "btn btn-outline-success btn-sm", id: "user_edit" %></td>
          <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '削除してよろしいですか？' }, class: "btn btn-outline-danger btn-sm", id: "user_destroy" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/admin/users/new.html.erb
<h3 class="text-center mt-3">管理画面からユーザー作成</h3>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<div class="content">
  <h1><%= @user.name %>さんのタスク一覧</h1>
  <p id="notice"><%= notice %></p>
  <table class="table list">
    <thead>
      <tr>
        <th>タスク名</th>
        <th>内容</th>
        <th>終了期限</th>
        <th>登録日時</th>
        <th>ステータス</th>
        <th>優先順位</th>
        <th>作成者</th>
      </tr>
    </thead>
    <tbody>
      <% @user.tasks.each do |task| %>
        <tr class="task_row">
          <td><%= task.task_name %></td>
          <td><%= task.task_detail %></td>
          <td><%= l task.expiry_date, format: :long %></td>
          <td><%= l task.created_at, format: :long %></td>
          <td><%= task.status %></td>
          <td><%= task.priority %></td>
          <td><%= task.user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '戻る', admin_users_path, class: 'btn btn-outline-success' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouExam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="w-100">
      <div class="text-right">
        <%= link_to "タスク登録", new_task_path, class: "mr-3"%>
        <%= link_to "タスク一覧", tasks_path, class: "mr-3"  %>
        <% if logged_in? %>
          <%= link_to "マイページ", user_path(current_user.id), class: "mr-3" %>
          <%= link_to "管理画面", admin_users_path, class: "mr-3" %>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "mr-3" %>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form_content">
  <h1>タスク</h1>
  <%= form_with(model: task, local: true) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> このプロパティの保存を禁止しました</h2>

        <ul>
          <% task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :task_name, "タスク名" %>
      <%= form.text_field :task_name, class: 'form-control mb-3' %>
    </div>

    <div class="field">
      <%= form.label :task_detail, "内容" %>
      <%= form.text_area :task_detail, class: 'form-control mb-3' %>
    </div>

    <div class="field">
      <%= form.label :expiry_date, "終了期限" %>
      <%= form.date_field :expiry_date, class: 'form-control mb-3'  %>
    </div>

    <div class="field">
      <%= form.label :status, "ステータス" %>
      <%= form.select :status, Task.statuses.keys.to_a,{},class: 'form-control mb-3'  %>
    </div>

    <div class="field">
      <%= form.label :priority, "優先順位" %>
      <%= form.select :priority, Task.priorities.keys.to_a, {},class: 'form-control mb-5'  %>
    </div>
    <div class="mb-5">
      <%= form.collection_check_boxes( :label_ids, Label.all, :id, :label_name, include_hidden: false) do |c| %>
        <%= c.label class: "chkl" do %>
          <%= c.check_box class: "chk" do %>
            <%= c.check_box + c.text %>
          <% end %>
            <%= c.label{c.text} %>
        <% end %>
      <% end %>
    </div>

    <%= form.submit class:'btn btn-primary mb-5' %>
  <% end %>
  <%= link_to '戻る', tasks_path, class: 'btn btn-outline-success' %>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="content">
  <h1>タスク一覧</h1>
  <p id="notice"><%= notice %></p>
  <div class="index_form w-50">
    <%= form_with(url: search_tasks_path, scope: :task, local: true, method: :get) do |form| %>
      <%= form.label :keyword, "タスク名" %>
      <%= form.text_field :keyword, value: @keyword, placeholder: "タイトル検索する", class: 'form-control mb-2' %>
      <%= form.label :status, "ステータス:" %>
      <%= form.select :status, Task.statuses.keys.to_a, {selected: @status, include_blank: true}, class: 'form-control mb-2' %>
      <%= form.label :sort_keyword, "ソート:" %>
      <%= form.select :sort_keyword,["なし","期限▼","期限▲","優先▼","優先▲"], {selected: @sort_keyword }, class: 'form-control mb-3' %>
      <%= form.label :label_keyword, "ラベル:" %>
      <%= form.select :label_id, Label.all.collect{|p|[p.label_name, p.id]}, {selected: @label_keyword, include_blank: true }, class: 'form-control mb-3' %>
      <%= form.submit "検索", class: 'btn btn-outline-info mb-3' %>
    <% end %>
  </div>

  <%= link_to 'タスクを登録する', new_task_path, class: 'btn btn-primary mb-3' %>

  <table class="table list">
    <thead>
      <tr>
        <th>タスク名</th>
        <th>内容</th>
        <th>終了期限</th>
        <th>登録日時</th>
        <th>ステータス</th>
        <th>優先順位</th>
        <th>作成者</th>
        <th>ラベル</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr class="task_row">
          <td><%= task.task_name %></td>
          <td><%= task.task_detail %></td>
          <td><%= l task.expiry_date, format: :long %></td>
          <td><%= l task.created_at, format: :long %></td>
          <td><%= task.status %></td>
          <td><%= task.priority %></td>
          <td><%= task.user.name %></td>
          <td>
            <% task.labels.pluck(:label_name).each do |label| %>
              <label class="btn btn-secondary btn-sm"><%= label %></label>
            <% end %>
          </td>
          <td><%= link_to '詳細', task, class: "btn btn-outline-primary btn-sm" %></td>
          <td><%= link_to '編集', edit_task_path(task), class: "btn btn-outline-success btn-sm" %></td>
          <td><%= link_to '削除', task, method: :delete, data: { confirm: '削除してよろしいですか？' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="detail">
  <h1>詳細</h1>
  <strong>タスク名：</strong>
  <p class="form-control mb-3">
    <%= @task.task_name %>
  </p>

  <strong>内容：</strong>
  <textarea readonly class="form-control mb-3">
    <%= @task.task_detail %>
  </textarea>

  <strong>終了期限：</strong>
  <p class="form-control mb-3">
    <%= @task.expiry_date %>
  </p>

  <strong>ステータス：</strong>
  <p class="form-control mb-3">
    <%= @task.status %>
  </p>

  <strong>優先順位：</strong>
  <p class="form-control mb-5">
    <%= @task.priority %>
  <div>
    <% @task.labels.pluck(:label_name).each do |label| %>
      <label class="btn btn-secondary btn-sm"><%= label %></label>
    <% end %>
  </div>
  </p><%= link_to '戻る', tasks_path, class: 'btn btn-outline-success' %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="detail">
  <h1>マイページ</h1>
  <strong>名前：</strong>
  <p class="form-control mb-3">
    <%= @user.name %>
  </p>
  <strong>email:</strong>
  <p readonly class="form-control mb-3">
    <%= @user.email %>
  </p>
  </p><%= link_to '戻る', tasks_path, class: 'btn btn-outline-success mt-3' %>
</div>